### ISSUE TITLE
Is not vertically responsive

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/modal#23]
Jamie Luetjen on Console noticed that the modal is not responsive to the height of the viewport. If the user decreases the height the modal does not reposition itself nor does it activate the scrollbars if necessary.
![screen shot 2017-12-19 at 3 02 48 pm](https://user-images.githubusercontent.com/13319923/34180953-b5998436-e4cd-11e7-82e9-b355f383fea0.png)

![screen shot 2017-12-19 at 3 02 56 pm](https://user-images.githubusercontent.com/13319923/34181076-17913b48-e4ce-11e7-9321-357688949baa.png)

**Comment by mhomolak** [comment]
What you're describing is a resize event. It will be responsive to whatever screen size it is loaded on.  If this is additional functionality you would like added we should discuss it.

@JasonLantz

**Comment by parkerpearson** [comment]
I think it is something we would like the modal to handle. Added to the
next dev and design for more discussion.

**Comment by StommePoes** [comment]
I'm going to vote for this, because I am thinking (hoping) a change in zoom levels would also trigger a resize event too since, if you zoom in after opening the modal, the modal goes offscreen similar to Parker's screenshots-- it *becomes* inaccessible even though it may have started as accessible.

Additionally GLP flagged the scrolling content as a bug https://agile-jira.pearson.com/browse/GLP-24763

We meant for this to allow scrolly material to be scrollable by keyboard, but truthfully this is only a scrollable area if the content height &gt; our content-area height. Otherwise, it shouldn't get an overflow nor the tabindex.

Since that change would require a listener like Parker's request, I suspect both can be hit with a single PR (unless it turns out that React can't do it and it gets complicated and needs to be separate PRs).

**Comment by mhomolak** [comment]
Handled in DES-882
